#!/usr/bin/perl 

sub dec2bin {
	($fld, $num) = @_;   
    my $str = unpack("B32", pack("N", $num));
    return substr($str,-$fld);
}

sub bin2dec {
	$num = shift;
    
print "NUM $num\n";
	my $n = unpack("N", pack("B32", substr("0" x 32 . $num, -32)));
	printf "SUBSTR".substr($num, 0,1)."\n";
	if(substr($num,0,1) eq "1") {
		$n -= 256;
	}
	return $n;
}

$a = $ARGV[0];
printf "a = %s bin = %s  dec = %s\n",
	$a, 
	dec2bin(8,$a),
	bin2dec(dec2bin(8,$a))
