#!/bin/bash

##        fontfamily
## font package to use for LaTeX documents (with pdflatex): TeXLive
## has bookman (Bookman), utopia  or  fourier  (Utopia),  fouriernc
## (New  Century Schoolbook), times or txfonts (Times), mathpazo or
## pxfonts or mathpple  (Palatino),  libertine  (Linux  Libertine),
## arev (Arev Sans), and the default lmodern, among others.
## 
FF="utopia" 
PDF="example-${FF}.pdf"
pandoc -N \
	--template=mytemplate.tex \
	--variable fontfamily="$FF" \
	--variable fontsize=12pt \
	--variable version=2.0 \
	MANUAL.txt \
	--toc \
	-o "$PDF"
atril "$PDF"
