#!/usr/bin/perl -n

if(/<!-- INCLUDE (.*) -->/) {
	open INCLUDE, "<$1" or die "no se pudo abrir $1";
	while($line = <INCLUDE>) {
	   print $line;
	}
	next;
} elsif(/<!-- INJECT (.*) -->/) {
		open INJECT, "$1|" or die "no se pudo abrir $1";
		while($line = <INJECT>) {
		   print $line;
		}
		next;
} elsif(/<!-- PROCESS (.*) -->/) {
		open PROCESS, "./macro < '$1'|" or die "No pude $1";
		while($line = <PROCESS>) {
		   print $line;
		}
} else { print; }
